# Generated by Django 5.1 on 2024-08-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('table', models.CharField(blank=True, max_length=255, null=True)),
                ('guid', models.PositiveIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('_modified', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
